### PR TITLE
add homepage wireframe

### LINKED ISSUE #1: Wire Frame
Initial visualization/representation of the finished product

### PR DESCRIPTION
**Pull request by dbradley555**

### CODE REVIEW

**Review by treecao — APPROVED** [review]
looks great

**Review by il1566144 — APPROVED** [review]
Great work

**Review by il1566144 — COMMENTED** [review]
Good work

**Review by il1566144 — COMMENTED** [review]
Nice

**Review by il1566144 — COMMENTED** [review]
nice

**Pull request merged**
